### PR TITLE
Fix to use `trace` for verbose debug logs

### LINKED ISSUE #91: log spamming
At `debug` level, this crate logs one line per **byte** of input, which makes the debug logs quite hard to read.

```
[2023-11-19T17:27:14Z DEBUG markdown::tokenizer] feed:    byte U+0020 to ParagraphInside
[2023-11-19T17:27:14Z DEBUG markdown::tokenizer] feed:    byte `s` (U+0073) to ParagraphInside
[2023-11-19T17:27:14Z DEBUG markdown::tokenizer] feed:    byte `e` (U+0065) to ParagraphInside
[2023-11-19T17:27:14Z DEBUG markdown::tokenizer] feed:    byte `c` (U+0063) to ParagraphInside
[2023-11-19T17:27:14Z DEBUG markdown::tokenizer] feed:    byte `r` (U+0072) to ParagraphInside
[2023-11-19T17:27:14Z DEBUG markdown::tokenizer] feed:    byte `e` (U+0065) to ParagraphInside
```

Maybe this log could be moved to `TRACE` level ?

### PR DESCRIPTION
**Pull request by lovasoa**
moves the most verbose logs from DEBUG level to TRACE, to make logs more readable

fixes #91

### CODE REVIEW

**Comment by wooorm** [comment]
I think there's docs on how to debug, could you change those too?

**Comment by lovasoa** [comment]
I updated the README. Is there anything else you want me to change ?

**Review by wooorm — APPROVED** [review]

**Comment by lovasoa** [comment]
great, thanks for merging ! Could you publish a new version, so that I can update [SQLPage](https://github.com/lovasoa/SQLpage)'s dependencies ?

**Comment by wooorm** [comment]
working on it! :)

**Comment by wooorm** [comment]
released!

**Pull request merged**
